RDKBACCL-322 : Observing build issues in latest tip of uwm
Reason for change: Observing below errors,
1.../../../git/inc/db_client.h:27:10: fatal error: mariadb/mysql.h: No such file or directory
|    27 | #include <mariadb/mysql.h>
|       |          ^~~~~~~~~~~~~~~~
2.| Makefile:3260: *** missing separator.  Stop.
| make[2]: *** [Makefile:370: all-recursive] Error 1
Test Procedure: Able to compile uwm
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>